[package]
name = "qrgen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
gif = { version = "0.13.1", default-features = false, features = ["std"] }
smolqr = { version = "0.1.0", path = ".." }
